# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [58]:
# your code here

import numpy as np

#### 2. Print your NumPy version.

In [59]:
# your code here
print(np.__version__)

1.16.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [60]:
# Method 1
a = np.random.random((2,3,5))
a

array([[[0.10399192, 0.12078598, 0.12014439, 0.62501393, 0.56467036],
        [0.0289747 , 0.00960962, 0.43467308, 0.52758916, 0.78686069],
        [0.7196375 , 0.76003604, 0.00714179, 0.6091045 , 0.80004466]],

       [[0.21275802, 0.50110086, 0.41641672, 0.26152589, 0.49509987],
        [0.52284138, 0.82668594, 0.9650576 , 0.16245001, 0.84817295],
        [0.57318749, 0.55731291, 0.11306804, 0.93861606, 0.67292029]]])

In [61]:
# Method 2
a = np.random.rand(2, 3, 5)
a

array([[[9.74591070e-02, 4.73709703e-01, 9.07242472e-01, 5.98995924e-01,
         4.42857555e-01],
        [1.73559006e-01, 2.54141545e-01, 3.80879987e-01, 2.44382178e-01,
         9.00499407e-01],
        [3.37594308e-01, 6.72352393e-02, 6.85607873e-01, 8.23593535e-01,
         7.19085699e-01]],

       [[8.39290799e-01, 6.89832667e-01, 5.85009543e-02, 1.63982328e-02,
         9.65175614e-01],
        [8.45610597e-01, 1.33299662e-01, 7.17187629e-01, 1.67254379e-01,
         2.80536598e-01],
        [1.96888924e-04, 2.22692766e-01, 3.16866961e-01, 5.01123277e-01,
         8.71597328e-01]]])

In [62]:
# Method 3
a = np.random.sample((2, 3, 5))
a

array([[[0.96262916, 0.90839864, 0.58269439, 0.94940268, 0.13648753],
        [0.80642985, 0.54037834, 0.57642164, 0.38336043, 0.68644602],
        [0.7452246 , 0.07663639, 0.45679414, 0.27762969, 0.49822283]],

       [[0.35246662, 0.79942077, 0.69111885, 0.59157238, 0.90907937],
        [0.03506399, 0.70787383, 0.79028675, 0.07015978, 0.45887758],
        [0.9500951 , 0.88812535, 0.83368941, 0.81890015, 0.64244024]]])

#### 4. Print *a*.


In [63]:
# your code here
print(a)

[[[0.96262916 0.90839864 0.58269439 0.94940268 0.13648753]
  [0.80642985 0.54037834 0.57642164 0.38336043 0.68644602]
  [0.7452246  0.07663639 0.45679414 0.27762969 0.49822283]]

 [[0.35246662 0.79942077 0.69111885 0.59157238 0.90907937]
  [0.03506399 0.70787383 0.79028675 0.07015978 0.45887758]
  [0.9500951  0.88812535 0.83368941 0.81890015 0.64244024]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [64]:
# your code here
b = np.ones((5, 2, 3))

#### 6. Print *b*.


In [65]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [66]:
# your code here
if a.size == b.size:
    print("They have the same size!")
else:
    print("They do not.")

They have the same size!


#### 8. Are you able to add *a* and *b*? Why or why not?


In [67]:
# your answer here
print("No we are not able to add because even tho they have the same size they have different shapes.")
#c = a + b

No we are not able to add because even tho they have the same size they have different shapes.


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [68]:
# your code here
c = np.transpose(b, axes=(1, 2, 0))
c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [69]:
# your code/answer here
d = a + c


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [70]:
# your code/answer here
print(a[0])
print(d[0])

# We just added 1? Is that it?

[[0.96262916 0.90839864 0.58269439 0.94940268 0.13648753]
 [0.80642985 0.54037834 0.57642164 0.38336043 0.68644602]
 [0.7452246  0.07663639 0.45679414 0.27762969 0.49822283]]
[[1.96262916 1.90839864 1.58269439 1.94940268 1.13648753]
 [1.80642985 1.54037834 1.57642164 1.38336043 1.68644602]
 [1.7452246  1.07663639 1.45679414 1.27762969 1.49822283]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [71]:
# your code here
e = a * c
print(e)

[[[0.96262916 0.90839864 0.58269439 0.94940268 0.13648753]
  [0.80642985 0.54037834 0.57642164 0.38336043 0.68644602]
  [0.7452246  0.07663639 0.45679414 0.27762969 0.49822283]]

 [[0.35246662 0.79942077 0.69111885 0.59157238 0.90907937]
  [0.03506399 0.70787383 0.79028675 0.07015978 0.45887758]
  [0.9500951  0.88812535 0.83368941 0.81890015 0.64244024]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [72]:
# your code/answer here
if np.array_equal(e, a):
    print("Yes they're the same!")
    
# Because c is the transpose of b who is only ones. So we are just multiplying a by 1

Yes they're the same!


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [73]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print(d_max)
print(d_min)
print(d_mean)

1.9626291599671268
1.0350639884303612
1.6042108830242185


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [74]:
# your code here
f = np.empty([2, 3, 5])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [75]:
# your code here

f = []
for x in np.nditer(d):
    if d_min < x < d_mean:
        f += [25]
    if d_mean < x < d_max:
        f += [75]
    if x == d_mean:
        f += [50]
    if x == d_min:
        f += [0]
    if x == d_max:
        f += [100]
    
        
f = np.reshape(f, d.shape) 
print(f)

[[[100  75  25  75  25]
  [ 75  25  25  25  75]
  [ 75  25  25  25  25]]

 [[ 25  75  75  25  75]
  [  0  75  75  25  25]
  [ 75  75  75  75  75]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [76]:
# your code here
print(d)
print(f)

[[[1.96262916 1.90839864 1.58269439 1.94940268 1.13648753]
  [1.80642985 1.54037834 1.57642164 1.38336043 1.68644602]
  [1.7452246  1.07663639 1.45679414 1.27762969 1.49822283]]

 [[1.35246662 1.79942077 1.69111885 1.59157238 1.90907937]
  [1.03506399 1.70787383 1.79028675 1.07015978 1.45887758]
  [1.9500951  1.88812535 1.83368941 1.81890015 1.64244024]]]
[[[100  75  25  75  25]
  [ 75  25  25  25  75]
  [ 75  25  25  25  25]]

 [[ 25  75  75  25  75]
  [  0  75  75  25  25]
  [ 75  75  75  75  75]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [77]:
# your code here

j = []
for x in np.nditer(d):
    if d_min < x < d_mean:
        j += ['B']
    if d_mean < x < d_max:
        j += ['D']
    if x == d_mean:
        j += ['C']
    if x == d_min:
        j += ['A']
    if x == d_max:
        j += ['E']
    
j = np.reshape(j, d.shape) 
print(j)

[[['E' 'D' 'B' 'D' 'B']
  ['D' 'B' 'B' 'B' 'D']
  ['D' 'B' 'B' 'B' 'B']]

 [['B' 'D' 'D' 'B' 'D']
  ['A' 'D' 'D' 'B' 'B']
  ['D' 'D' 'D' 'D' 'D']]]
